export const initialItems = [
  { id: 1, name: "Ve", eBlere: true },
  { id: 2, name: "Vaj", eBlere: false },
  { id: 3, name: "Vaj ulliri", eBlere: false },
  { id: 4, name: "Tërshërë", eBlere: false },
  { id: 5, name: "Cornflexa", eBlere: false },
  { id: 6, name: "Kos", eBlere: false },
  { id: 7, name: "Uthull molle", eBlere: false },
  { id: 8, name: "Krip", eBlere: false },
  { id: 9, name: "Sheqer", eBlere: false },
  { id: 10, name: "Miell", eBlere: false },
  { id: 11, name: "Çajra (Rusi)", eBlere: false },
  { id: 12, name: "Kafe turke", eBlere: false },
  { id: 13, name: "Vegetë", eBlere: false },
  { id: 14, name: "Biber", eBlere: false },
  { id: 15, name: "Biber t zi", eBlere: false },
  { id: 16, name: "Origano", eBlere: false },
  { id: 17, name: "Majdanoz", eBlere: false },
  { id: 18, name: "Makarona", eBlere: false },
  { id: 19, name: "Oriz", eBlere: false },
  { id: 20, name: "Pasul", eBlere: false },
  { id: 21, name: "Ullinj", eBlere: false },
  { id: 22, name: "Zarzavate të ngrira", eBlere: false },
  { id: 23, name: "Patate", eBlere: false },
  { id: 24, name: "Qepë", eBlere: false },
  { id: 25, name: "Hudhër", eBlere: false },
  { id: 26, name: "Pemë", eBlere: false },
  { id: 27, name: "Nuts të ndryshme", eBlere: false },
  { id: 28, name: "Kungulleshka", eBlere: false },
  { id: 29, name: "Borania", eBlere: false },
  { id: 30, name: "Patëllxhan", eBlere: false },
  { id: 31, name: "Purri", eBlere: false },
  { id: 32, name: "Domate", eBlere: false },
  { id: 33, name: "Sallatë jeshile", eBlere: false },
  { id: 34, name: "Kërpudha", eBlere: false },
  { id: 35, name: "Çokollatë e zezë", eBlere: false },
  { id: 36, name: "Bullgur", eBlere: false },
  { id: 37, name: "Thjerrëza", eBlere: false },
  { id: 38, name: "Qumësht", eBlere: false },
  { id: 39, name: "Nesquik", eBlere: false },
  { id: 40, name: "Djath", eBlere: false },
  { id: 41, name: "Kaçkavall", eBlere: false },
  { id: 42, name: "Mish të kuq", eBlere: false },
  { id: 43, name: "Mish të terur", eBlere: false },
  { id: 44, name: "Mish i bluar", eBlere: false },
  { id: 45, name: "Peshqi", eBlere: false },
  { id: 46, name: "Peshk konzervë", eBlere: false },
  { id: 47, name: "Proshutë", eBlere: false },
  { id: 48, name: "Gjoks pule", eBlere: false },
  { id: 49, name: "Faks", eBlere: false },
  { id: 50, name: "Aromatizues për tesha", eBlere: false },
  { id: 51, name: "Aromatizues për shole", eBlere: false },
  { id: 52, name: "Shampon për duar", eBlere: false },
  { id: 53, name: "Shampon për enë", eBlere: false },
  { id: 54, name: "Shampona për flokë", eBlere: false },
  { id: 55, name: "Shampon trupi", eBlere: false },
  { id: 56, name: "Kollodont", eBlere: false },
  { id: 57, name: "Brusha për dhëmbë", eBlere: false },
  { id: 58, name: "Gricka të ndryshme", eBlere: false },
  { id: 59, name: "Fara", eBlere: false },
  { id: 60, name: "Folje", eBlere: false },
  { id: 61, name: "Trolleksa", eBlere: false },
  { id: 62, name: "Sfungjer enësh", eBlere: false },
  { id: 63, name: "Limon", eBlere: false },
  { id: 64, name: "Pesto", eBlere: false },
  { id: 65, name: "Margarin", eBlere: false },
  { id: 66, name: "Mak", eBlere: false },
  { id: 67, name: "Keksa", eBlere: false },
  { id: 68, name: "Pije", eBlere: false },
  { id: 69, name: "Domestos", eBlere: false },
  { id: 70, name: "Toilet paper", eBlere: false },
  { id: 71, name: "Kastravec turshi", eBlere: false },
  { id: 72, name: "Rollne per kuzhinë", eBlere: false },
  { id: 73, name: "Schmand", eBlere: false },
  { id: 74, name: "Fara chia", eBlere: false },
  { id: 75, name: "Brokoli", eBlere: false },
  { id: 76, name: "Kese frizi", eBlere: false },
];
